name: Build and Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker Compose
      run: docker-compose build

    - name: Save Docker Image
      run: |
        docker save -o cicd_clouds.tar devops3_clouds
        
    - name: List Workspace Contents
      run: |
        ls -R $GITHUB_WORKSPACE

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v2
      with:
        name: devops3_clouds
        path: $GITHUB_WORKSPACE/cicd_clouds.tar
